[package]
name = "rust-beginner"
version = "0.1.0"
edition = "2021"

[dependencies]
rmp-serde = "1.3.0"
serde = {version = "1.0.215", features = ["derive"]}
serde_json = "1.0.133"
serde_yml = "0.0.12"
